---
# this is the test of ibmi_object_find
- name: this is a test of ibmi_object_find
  hosts: all
  vars:
    usrprf: 'DAVETEST'
    homedir: '/home/davetest'
    curlib: "{{ usrprf }}"
    sshfile: 'ansible_id_rsa.pub'
  gather_facts: no
  collections:
    - ibm.power_ibmi

  tasks:
    - name : test the object ibmi_object_find
      ibmi_object_find :
        object_name: "{{ item.obj }}"
        lib_name: "{{ item.lib }}"
        object_type_list: "{{ item.type }}"
      register: object_find
      with_items:
        - { obj: 'DAVETEST', lib: 'QSYS', type: '*USRPRF'}
        - { obj: 'DAVETEST', lib: 'QSYS', type: '*LIB'}

    - name : print output
      debug:
        msg: "{{ object_find }}"

    - name: Count the length of object_lsit
      debug:
        msg: "Test count: {{ item.object_list | length }}"
      with_items: "{{ object_find.results }}"

    
